### ISSUE TITLE
 [Question]: Query on the Role of Attester and Author in the eRezept Document Process

### ISSUE THREAD

**Issue by HiepPP** [gematik/eRezept-Examples#19]
Dear gematik,

I hope this message finds you well. I have a few queries pertaining to the roles of the 'attester' and 'author' within the eRezept document framework, specifically referencing the example XML provided.

Considering the instance of Dr. "Ben" who possesses the Practitioner ID "d6f3b55d-3095-4655-96dc-da3bec21271c", I understand he is responsible for signing and dispatching the eRezept document. Is there a possibility that he could also be the creator of the eRezept document?

It appears that the 'attester' might be the creator of the eRezept, and the 'author' is likely the doctor who signs and sends the document. Could you confirm if my understanding is correct?

I would appreciate your guidance and clarification on these matters.

Thank you in advance for your assistance and I look forward to your response.

XML link: [https://github.com/gematik/eRezept-Examples/blob/main/Standalone-Examples/eRezept(KBV)/1.1.0/ec6059d9-72a0-4ba3-8535-6ffcc0c4279b.xml](url)

**Comment by florianschoffke** [comment]
Hello @HiepPP,
The prescription is defined within the KBV documents, specifically the "[Technische Anlage zur elektronischen Arnzneimittelverordnung"](https://update.kbv.de/ita-update/DigitaleMuster/ERP/KBV_ITA_VGEX_Technische_Anlage_ERP.pdf).

Under function "P36-34" you have the explanation for how to use .author and .attester. Hopefully Deepl will be helpful ;) 

In short: .author is always the author of the document. If that author is a practitioner in training, then the .attester is a certified practitioner that is "responsible" for this document but who did not create ist.

Did my explanation and the document that I provided make sense?

**Comment by HiepPP** [comment]
Hi @florianschoffke, I'm grateful for the guidance you've provided, thank you 👍
