### ISSUE TITLE
Aktualisiertes Stylesheet für Mehrfachverordnungen

### ISSUE THREAD

**Issue by sungaila** [gematik/eRezept-Examples#4]
In diesem Repository gibt es eine Beispielmehrfachverordnung in einer HTML-Darstellung: https://github.com/gematik/eRezept-Examples/blob/dev/End-to-End-Examples/3_01.07.2022/PZN_Mehrfachverordnung_Vorschau/PZN_MV_4/PZN_MV4_VerordnungArzt.html

In meinem Browser wird diese wie folgt dargestellt:
![PZN_MV4_VerordnungArzt.html](https://user-images.githubusercontent.com/12021771/215457858-e9e52dac-a0a5-4c99-9d0e-21d1b6492ed3.png)

In der Verordnungszeile kommt folgender Text vor:
> Mehrfachverordnung 4 von 4: Einlösbar vom 01.12.2021 bis 31.03.2022

Wird dieser Text durch das Stylesheet / die XSLT-Datei generiert? Wenn ja, wird ein aktualisiertes Stylesheet in dieses Repo hochgeladen? Falls nein, wo wird dieser Textbaustein definiert (FHIR)?

**Comment by florianschoffke** [comment]
Hallo @sungaila,
habe ich die Anfrage richtig verstanden, dass du wissen möchtest, wo die Entsprechenden Angaben im FHIR-Profil zu finden sind?

Die Elemente der MVO findest du im [KBV_PR_ERP_Prescription](https://simplifier.net/erezept/kbvprerpprescription) Profil.
MedicationRequest.extension:Mehrfachverordnung.extension enthält die Einträge für:
* Kennzeichen (handelt es sich um eine MVO? true/false)
* Nummerierung (um welches Rezept in der MVO handelt es sich? Als Ratio: z.B. 2 von 4)
* Zeitraum (wie lange ist die MVO gültig? von/bis)
* ID (Eindeutige UUID für die MVO)

Das aktuelle Stylesheet für KBV_erp findest du [hier](https://update.kbv.de/ita-update/DigitaleMuster/ERP/III_2023/).

Hoffe, dass das weiter hilft. Hat das deine Frage beantwortet?

**Comment by sungaila** [comment]
> Das aktuelle Stylesheet für KBV_erp findest du [hier](https://update.kbv.de/ita-update/DigitaleMuster/ERP/III_2023/).

Genau das habe ich gesucht! Im neusten Stylesheet wird die Verschreibungszeile für Mehrfachverordnungen korrekt befüllt.

Vielen Dank!
