### ISSUE TITLE
Testfälle mit richtigem Datum versehen, damit Ausstellungsdatum zum Profil-Zeitraum passt

### ISSUE THREAD

**Issue by joergreichert** [gematik/eRezept-Examples#48]
Beim Regressionstesten war mit der neuen Referenzvalidator-Version jetzt aufgefallen, dass nicht mehr alle Fehler bei den Negativ-Testfällen gefunden worden sind:
https://github.com/gematik/app-referencevalidator/issues/22

Nach Anpassen der authoredOn-Daten gingen sie dann wieder. Es wäre schön, wenn man die Testdaten unverändert nutzen könnte (haben sie derzeit bei uns als Git-Submodul liegen im Projekt liegen, und nutzen sie, um zu testen, ob der Referenzvalidator weiterhin richtig bei uns eingebunden ist).

**Comment by Hendrejvr** [comment]
@joergreichert Danke für den Hinweis. Pull Request erstellt, und nach dem Review werde ich ihn mergen
